### ISSUE TITLE
Feat : AWS 인프라 구성 ( EC2 / RDS / S3 ) 

### ISSUE THREAD

**Issue by TLOWAC** [dnd-side-project/dnd-10th-1-backend#16]
# ✨ Feature

## 어떤 작업을 할 예정인가요?
- [x] EC2 / RDS / S3 생성 
- [x]  IAM 유저 생성 - [창훈, 혜빈]
- [x] VPC / Subnet / SG 정의 사항 인프라 구성도에 반영 ( [FigGem](https://www.figma.com/file/RxGJv90H6ESsVpRabOuSqB/%EC%8B%9C%EC%8A%A4%ED%85%9C-%EC%95%84%ED%82%A4%ED%85%8D%EC%B3%90-%5B%EB%B0%B1%EC%97%94%EB%93%9C%5D?type=whiteboard&node-id=0-1&t=yJM40OWIxY4XC5wM-0) ) 

## 기타

**Comment by hyebinnn** [comment]
- VPC / Subnet / SG 포함한 AWS 인프라 아키텍쳐 
<img width="1133" alt="image" src="https://github.com/dnd-side-project/dnd-10th-1-backend/assets/76420055/87cd74dd-daa1-44cf-b3b2-94cd8eafef12">

**Comment by hyebinnn** [comment]
S3 버킷 생성 완료

**Comment by hyebinnn** [comment]
- AWS 인프라 아키텍쳐 수정 
  - 서브넷을 4개로 늘렸습니다. 즉, RDS와 EC2를 재생성하였고 RDS와 EC2가 같은 az에 있도록 구성하였습니다.
  - EC2를 Linux -> Ubuntu로 재생성하였습니다.
 
<img width="830" alt="image" src="https://github.com/dnd-side-project/dnd-10th-1-backend/assets/76420055/1bd67986-5cb0-49d9-9eb9-9ff84808d284">
